- matlab-version: R2021a
  python-version: '3.9'
  skip-pynwb-compatibilty-test-for-tutorial: '1'
- matlab-version: R2021b
  python-version: '3.9'
  skip-pynwb-compatibilty-test-for-tutorial: '1'
- matlab-version: R2022a
  python-version: '3.9'
  skip-pynwb-compatibilty-test-for-tutorial: '0'
- matlab-version: R2022b
  python-version: '3.9'
  skip-pynwb-compatibilty-test-for-tutorial: '0'
- matlab-version: R2023a
  python-version: '3.10'
  skip-pynwb-compatibilty-test-for-tutorial: '0'
- matlab-version: R2023b
  python-version: '3.10'
  skip-pynwb-compatibilty-test-for-tutorial: '0'
- matlab-version: R2024a
  python-version: '3.11'
  skip-pynwb-compatibilty-test-for-tutorial: '0'
- matlab-version: R2024b
  python-version: '3.11'
  skip-pynwb-compatibilty-test-for-tutorial: '0'