% PynwbTutorialTest - Unit test for testing the PyNWB tutorials.
%
%   This test reads tutorial files from the directory specified by the
%   PYNWB_REPO_DIR environment variable, which should point to a local clone
%   of the pynwb repository. If the tutorial creates nwb file(s), the test
%   will also try to open these with matnwb.

classdef (SharedTestFixtures = {tests.fixtures.SetEnvironmentVariableFixture}) ...
        PynwbTutorialTest < matlab.unittest.TestCase

    properties (TestParameter)
        % tutorialFile - A cell array where each cell is the name of a
        % tutorial file. testTutorial will run on each file individually.
        TutorialFile = listTutorialFiles();
    end

    properties (Constant)
        % SkippedTutorials - Tutorials from pynwb to skip
        SkippedTutorials = {...
            'plot_read_basics.py', ...      % Downloads file from dandi archive, does not export nwb file
            'streaming.py', ...             % Requires that HDF5 library is installed with the ROS3 driver enabled which is not a given
            'object_id.py', ...             % Does not export nwb file
            'plot_configurator.py', ...     % Does not export nwb file
            'plot_zarr_io', ...             % Does not export nwb file in nwb format
            'brain_observatory.py', ...     % Requires allen sdk
            'extensions.py'};               % Discrepancy between tutorial and schema: https://github.com/NeurodataWithoutBorders/pynwb/issues/1952

        % SkippedFiles - Name of exported nwb files to skip reading with matnwb
        SkippedFiles = {'family_nwb_file_0.nwb'} % requires family driver from h5py

        % FileDependencies - Additional repo-relative files needed by tutorials
        FileDependencies = {'docs/source/figures/logo_pynwb.png'}
    end

    methods (TestClassSetup)
        function setupClass(testCase)
            testCase.applyFixture(matlab.unittest.fixtures.WorkingFolderFixture);

            pynwbRepoDir = getenv('PYNWB_REPO_DIR');
            testCase.assumeNotEmpty(pynwbRepoDir, ...
                'PYNWB_REPO_DIR is not set, skipping PyNWB tutorial tests');

            testCase.copyTutorialFilesToWorkingFolder(pynwbRepoDir)
            testCase.copyTutorialDependenciesToWorkingFolder(pynwbRepoDir)
        end
    end

    methods (TestMethodTeardown)
        function teardownMethod(testCase) %#ok<MANU>
            % Clear/delete all nwb files
            nwbListing = dir('*.nwb');
            for i = 1:numel(nwbListing)
                delete(fullfile(nwbListing(i).folder, nwbListing(i).name))
            end
        end
    end

    methods (Test, TestTags = {'UsesPython'})
        function testTutorial(testCase, TutorialFile)
            galleryFolder = fullfile(pwd, 'docs', 'gallery');
            tutorialFilePath = fullfile(galleryFolder, TutorialFile);
            pythonExecutable = getenv("PYTHON_EXECUTABLE");
            [status, cmdout] = system(sprintf('"%s" "%s"', pythonExecutable, tutorialFilePath));
            if status ~= 0
                if contains(cmdout, "ModuleNotFoundError: No module named 'hdf5plugin'")
                    % pass - hdf5plugin not required
                else
                    [~, tutorialName] = fileparts(TutorialFile);
                    error('Failed to run python tutorial "%s":\n%s', tutorialName, cmdout)
                end
            end
            testCase.testReadTutorialNwbFileWithMatNwb()
        end
    end

    methods
        function testReadTutorialNwbFileWithMatNwb(testCase)
            % Retrieve all files generated by the tutorial
            nwbListing = dir('*.nwb');
            for i = 1:numel(nwbListing)
                nwbFilename = nwbListing(i).name;
                if any(strcmp(nwbFilename, tests.system.tutorial.PynwbTutorialTest.SkippedFiles))
                    continue
                end
                try
                    % NB: Need to specify savedir to current directory (.) in
                    % order to generate schema in working directory for test
                    nwbFile = nwbRead(nwbFilename, 'savedir', '.'); %#ok<NASGU>
                catch ME
                    error(ME.message)
                end
            end
        end
    end
    
    methods(Access = private)
        function copyTutorialFilesToWorkingFolder(testCase, pynwbRepoDir)
        % copyTutorialFilesToWorkingFolder - Copy the pynwb tutorial files
        % to the temporary working folder used by this test suite.
            sourceGalleryFolder = fullfile(pynwbRepoDir, 'docs', 'gallery');
            targetGalleryFolder = fullfile(pwd, 'docs', 'gallery');
            [status, msg] = copyfile(sourceGalleryFolder, targetGalleryFolder, 'f');
            testCase.assertTrue(status, ...
                sprintf('Failed to copy docs/gallery into test working folder: %s', msg));
        end
        
        function copyTutorialDependenciesToWorkingFolder(testCase, pynwbRepoDir)
            for i = 1:numel(testCase.FileDependencies)
                relativePath = testCase.FileDependencies{i};
                sourcePath = fullfile(pynwbRepoDir, relativePath);
                targetPath = fullfile(pwd, relativePath);
                targetDir = fileparts(targetPath);
                if ~isfolder(targetDir)
                    mkdir(targetDir);
                end
                [status, msg] = copyfile(sourcePath, targetPath, 'f');
                testCase.assertTrue(status, ...
                    sprintf('Failed to copy tutorial dependency "%s": %s', relativePath, msg));
            end
        end
    end
end

function tutorialFiles = listTutorialFiles()
% listTutorialFiles - List gallery-relative paths of tutorial files (exclude skipped files)
%
%   Returns paths relative to the gallery folder, e.g. "general/ecephys.py",
%   so that test names are readable. The full path is reconstructed in testTutorial.
    
    pynwbRepoDir = getenv('PYNWB_REPO_DIR');
    if isempty(pynwbRepoDir)
        tutorialFiles = {''};
        return
    end

    galleryFolder = fullfile(pynwbRepoDir, 'docs', 'gallery');
    
    pyFileListing = dir(fullfile(galleryFolder, '**', '*.py'));
    pyFileListing = excludeSkippedFiles(pyFileListing);

    absolutePaths = fullfile({pyFileListing.folder}, {pyFileListing.name});
    tutorialFiles = replace(absolutePaths, [galleryFolder, filesep], '');
end

function tutorialFileListing = excludeSkippedFiles(pyFileListing)
% excludeSkippedFiles - Exclude tutorial files to skip from tests
    allNames = {pyFileListing.name};
    namesToSkip = tests.system.tutorial.PynwbTutorialTest.SkippedTutorials;
    keep = ~ismember(allNames, namesToSkip);
    tutorialFileListing = pyFileListing(keep);
end
