classdef (SharedTestFixtures = {tests.fixtures.GenerateCoreFixture, tests.fixtures.SetEnvironmentVariableFixture}) ...
        TutorialTest <  matlab.unittest.TestCase
% TutorialTest - Unit test for testing the matnwb tutorials.
%
%   This test will test most tutorial files (while skipping tutorials with 
%   dependencies) If the tutorial creates an nwb file, the test will also try 
%   to open this with pynwb and run nwbinspector on the file.

%   Notes: 
%   - Requires MATLAB 2019b or later to run py.* commands.
%
%   - pynwb must be installed in the python environment returned by pyenv()
%
%   - Running NWBInspector as a Python package within MATLAB on GitHub runners 
%     currently encounters compatibility issues between the HDF5 library and 
%     h5py. As a workaround in this test, the CLI interface is used to run 
%     NWBInspector and the results are manually parsed. This approach is not 
%     ideal, and hopefully can be improved upon.

    properties
        MatNwbDirectory
    end

    properties (Constant)
        NwbInspectorSeverityLevel = 1
    end

    properties (TestParameter)
        % TutorialFile - A cell array where each cell is the name of a
        % tutorial file. testTutorial will run on each file individually
        tutorialFile = listTutorialFiles();
    end

    properties (Constant)
        SkippedTutorials = {...
            'basicUsage.mlx', ...  % depends on external data
            'convertTrials.m', ... % depends on basicUsage output
            'formatStruct.m', ...  % Actually a utility script, not a tutorial
            'read_demo.mlx', ...   % depends on external data
            'read_demo_dandihub.mlx', ... % depends on external data
            'remote_read.mlx'};    % Uses nwbRead on s3 url, potentially very slow
        
        % SkippedFiles - Name of exported nwb files to skip reading with pynwb
        SkippedFiles = {'testFileWithDataPipes.nwb'} % does not produce a valid nwb file
    end

    methods (TestClassSetup)
        function setupClass(testCase)
            
            % Get the root path of the matnwb repository
            rootPath = tests.util.getProjectDirectory();
            tutorialsFolder = fullfile(rootPath, 'tutorials');
            
            testCase.MatNwbDirectory = rootPath;

            % Use a fixture to add the folder to the search path
            %testCase.applyFixture(matlab.unittest.fixtures.PathFixture(rootPath));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(tutorialsFolder));
        end
    end

    methods (TestMethodSetup)
        function setupMethod(testCase)
            testCase.applyFixture(matlab.unittest.fixtures.WorkingFolderFixture);
            %generateCore('savedir', '.');
        end
    end
    
    methods (Test)
        function testTutorial(testCase, tutorialFile) %#ok<INUSD>
            % Intentionally capturing output, in order for tests to cover
            % code which overloads display methods for nwb types/objects.
            C = evalc( 'run(tutorialFile)' ); %#ok<NASGU>
            
            skipChecks = getenv("SKIP_PYNWB_COMPATIBILITY_TEST_FOR_TUTORIALS");
            skipChecks = ~isempty(skipChecks) && logical(str2double(skipChecks));
            if skipChecks
                % pass
            else
                testCase.readTutorialNwbFileWithPynwb()
                testCase.inspectTutorialFileWithNwbInspector()
            end
        end
    end

    methods 
        function readTutorialNwbFileWithPynwb(testCase)
            % Retrieve all files generated by tutorial
            nwbFileNameList = testCase.listNwbFiles();
            for nwbFilename = nwbFileNameList
                try
                    [nwbObject, nwbFileCleanup] = tests.util.readWithPynwb(nwbFilename); %#ok<ASGLU>
                    testCase.verifyNotEmpty(nwbObject, 'The NWB file should not be empty.');
                catch ME
                    error(ME.message)
                end
            end
        end
    
        function inspectTutorialFileWithNwbInspector(testCase)
            % Retrieve all files generated by tutorial
            nwbFileNameList = testCase.listNwbFiles();
            for nwbFilename = nwbFileNameList
                results = inspectNwbFile(nwbFilename);
                if isempty(results)
                    return
                end

                results = table2struct(results);
                results = testCase.nwbinspectorImportanceToNumber(results);
                results = testCase.filterNWBInspectorResults(results);

                for j = 1:numel(results)
                    testCase.verifyLessThan(results(j).importance, testCase.NwbInspectorSeverityLevel, ...
                        sprintf('Message: %s\nLocation: %s\n File: %s\n', ...
                        string(results(j).message), results(j).location, results(j).file_path))
                end
            end
        end
    end

    methods (Access = private)
        function nwbFileNames = listNwbFiles(testCase)
            nwbListing = dir('*.nwb');
            nwbFileNames = string( {nwbListing.name} );
            nwbFileNames = setdiff(nwbFileNames, testCase.SkippedFiles);
            assert(isrow(nwbFileNames), 'Expected output to be a row vector')
            if ~isscalar(nwbFileNames)
                if iscolumn(nwbFileNames)
                    nwbFileNames = transpose(nwbFileNames);
                end
            end
        end
    end

    methods (Static, Access = private)
        function results = nwbinspectorImportanceToNumber(results)
            importanceLevels = containers.Map(...
                ["BEST_PRACTICE_SUGGESTION", ...
                "BEST_PRACTICE_VIOLATION", ...
                "CRITICAL", ...
                "PYNWB_VALIDATION", ...
                "ERROR"], 0:4 );
            for i = 1:numel(results)
                results(i).importance = importanceLevels(results(i).importance);
            end
        end

        function resultsOut = filterNWBInspectorResults(resultsIn)
            CHECK_IGNORE = [...
                "check_image_series_external_file_valid", ...
                "check_regular_timestamps"
                ];
            [resultsIn(:).ignore] = deal(false);
            for i = 1:numel(resultsIn)
                resultsIn(i).ignore = any(strcmp(CHECK_IGNORE, resultsIn(i).check_function_name));
            
                % Special cases to ignore
                if resultsIn(i).location == "/acquisition/ExternalVideos" && ...
                        resultsIn(i).check_function_name == "check_timestamps_match_first_dimension"
                    resultsIn(i).ignore = true;
                elseif resultsIn(i).location == "/acquisition/SpikeEvents_Shank0" && ...
                    resultsIn(i).check_function_name == "check_data_orientation"
                    % Data for this example is actually longer in another dimension
                    % than time.
                    resultsIn(i).ignore = true;
                end
            end
            resultsOut = resultsIn;
            resultsOut([resultsOut.ignore]) = [];
        end
    end
end

function tutorialNames = listTutorialFiles()
% listTutorialFiles - List names of all tutorial files (exclude skipped files)
    rootPath = tests.util.getProjectDirectory();
    L = cat(1, ...
        dir(fullfile(rootPath, 'tutorials', '*.mlx')), ...
        dir(fullfile(rootPath, 'tutorials', '*.m')) ...
        );

    L( [L.isdir] ) = []; % Ignore folders
    tutorialNames = setdiff({L.name}, tests.system.tutorial.TutorialTest.SkippedTutorials);
end
