coverage:
  range: "90...100"
  status:
    project:
      default:
        target: 90 # Set the desired coverage target as 90%
        threshold: 1 # Allowable drop in coverage
    patch:
      default:
        # 75% of the changed code must be covered by tests
        threshold: 25
        only_pulls: true
