membrane_potential = types.simulation_output.CompartmentSeries('gid', [1, 2, 3], ...
    'index_pointer', [1, 2, 3], ...
    'data', [[1., 2., 4.], [1., 2., 4.]]', ...
    'element_id', [0, 0, 0], ...
    'compartment_position', [1., 1., 1.], ...
    'data_unit', 'µV', ...
    'starting_time_rate', 100.);

date = datetime(2018, 3, 1, 12, 0, 0);
session_start_time = datetime(date,'Format','yyyy-MM-dd''T''HH:mm:SSZZ',...
    'TimeZone','local');
nwb = nwbfile('session_description', 'a test NWB File', ...
    'identifier', 'mouse004_day4', ...
    'session_start_time', session_start_time);

nwb.acquisition.set('membrane_potential', membrane_potential);

nwbExport(nwb, 'membrane_potential.nwb')

nwb2 = nwbRead('membrane_potential.nwb');