function tf = isSchemaDefinedTableColumn(propertyInfo, namespace)
% isSchemaDefinedTableColumn - Determine whether a property stores a 
% schema-defined DynamicTable column.

    tf = isscalar(propertyInfo) ...
        && isa(propertyInfo, 'file.Dataset') ...
        && ~propertyInfo.isConstrainedSet ...
        && ~isempty(propertyInfo.type) ...
        && file.internal.isDescendantOf( ...
            propertyInfo.type, namespace, 'VectorData');
end
