function addTableColumn(DynamicTable, subTable)
error('NWB:DynamicTable', ...
    ['Using MATLAB tables as input to the addColumn DynamicTable method has '...
    'been deprecated. Please, use key-value pairs instead'])