classdef CheckConstantTest < matlab.unittest.TestCase
% CheckConstantTest - Unit tests for types.util.checkConstant.

    methods (Test)
        function testMatchingCharValueReturnsConstant(testCase)
            value = types.util.checkConstant( ...
                'data_unit', 'volts', 'volts', 'types.core.ElectricalSeries');

            testCase.verifyEqual(value, 'volts')
        end

        function testMismatchedCharValueErrors(testCase)
            testCase.verifyError( ...
                @() types.util.checkConstant( ...
                    'data_unit', ...
                    'volts', ...
                    'millivolts', ...
                    'types.core.ElectricalSeries'), ...
                'NWB:Type:ReadOnlyProperty')
        end

        function testMatchingNumericValueReturnsCorrectedDtype(testCase)
            expectedValue = types.util.correctType(1, 'int32');

            value = types.util.checkConstant( ...
                'timestamps_interval', ...
                expectedValue, ...
                1, ...
                'types.core.SpikeEventSeries');

            testCase.verifyEqual(value, expectedValue)
            testCase.verifyClass(value, class(expectedValue))
        end

        function testMismatchedNumericValueErrors(testCase)
            testCase.verifyError( ...
                @() types.util.checkConstant( ...
                    'timestamps_interval', ...
                    1, ...
                    2, ...
                    'types.core.SpikeEventSeries'), ...
                'NWB:Type:ReadOnlyProperty')
        end
    end
end
