classdef CheckTypeTest < matlab.unittest.TestCase
% CheckTypeTest - Unit tests for types.util.checkType.

    methods (Test)
        function testMatchingTypePasses(testCase)
            value = types.hdmf_common.VectorData( ...
                'description', 'a column', 'data', (1:3)');
            testCase.verifyWarningFree( ...
                @() types.util.checkType( ...
                    'col', 'types.hdmf_common.VectorData', value))
        end

        function testWrongTypeErrorsInEditContext(testCase)
            value = types.hdmf_common.VectorData( ...
                'description', 'a column', 'data', (1:3)');
            testCase.verifyError( ...
                @() types.util.checkType( ...
                    'region', 'types.hdmf_common.DynamicTableRegion', value), ...
                'NWB:CheckType:InvalidNeurodataType')
        end

        function testWrongTypeWarnsInReadContext(testCase)
            value = types.hdmf_common.VectorData( ...
                'description', 'a column', 'data', (1:3)');
            [~, cleanup] = matnwb.common.validation.internal.context("read"); %#ok<ASGLU>

            testCase.verifyWarning( ...
                @() types.util.checkType( ...
                    'region', 'types.hdmf_common.DynamicTableRegion', value), ...
                'NWB:CheckType:InvalidNeurodataType')
        end

        function testUnknownExpectedTypeAlwaysErrors(testCase)
            [~, cleanup] = matnwb.common.validation.internal.context("read"); %#ok<ASGLU>

            testCase.verifyError( ...
                @() types.util.checkType('x', 'types.core.NotARealType', 5), ...
                'NWB:CheckType:UnknownNeurodataType')
        end
    end
end
