classdef CheckDtypeTest < matlab.unittest.TestCase
% CheckDtypeTest - Unit test for functions in +types namespace.

    methods (Test)

        function testCompoundTypeWithTooManyFields(testCase)

            typeDescriptor = struct(...
                'a', 'uint8', ...
                'b', 'char');

            testValueStruct = struct(...
                'a', 1, ...
                'b', 2, ...
                'c', 3);

            testValueTable = struct2table(testValueStruct);

            testValueMap = containers.Map(...
                fieldnames(testValueStruct), ...
                struct2cell(testValueStruct));

            testCase.verifyError(...
                @() types.util.checkDtype('struct', typeDescriptor, testValueStruct), ...
                'NWB:CheckDType:InvalidValue')
            testCase.verifyError(...
                @() types.util.checkDtype('map', typeDescriptor, testValueMap), ...
                'NWB:CheckDType:InvalidValue')
            testCase.verifyError(...
                @() types.util.checkDtype('table', typeDescriptor, testValueTable), ...
                'NWB:CheckDType:InvalidValue')
        end
    end

    methods (Static)
        function 

        end
    end
end