classdef DynamicTableCheckConfigTest < matlab.unittest.TestCase
% DynamicTableCheckConfigTest - Unit tests for DynamicTable schema checks.

    methods (Test)
        function testInvalidColnamesErrorsInReadContext(testCase)
            % A non-text colnames is a structural defect, not a recoverable
            % schema deviation, so it is a hard error even when reading.
            [~, cleanup] = matnwb.common.validation.internal.context("read");

            testCase.verifyError( ...
                @() types.hdmf_common.DynamicTable( ...
                    'description', 'invalid colnames', ...
                    'colnames', 1), ...
                'NWB:DynamicTable:InvalidColumnNames')
        end

        function testMismatchedColumnHeightsWarnInReadContext(testCase)
            [~, cleanup] = matnwb.common.validation.internal.context("read");

            testCase.verifyWarning( ...
                @() types.hdmf_common.DynamicTable( ...
                    'description', 'mismatched column heights', ...
                    'colnames', {'columnA', 'columnB'}, ...
                    'id', types.hdmf_common.ElementIdentifiers( ...
                        'data', int64(0:2)), ...
                    'columnA', types.hdmf_common.VectorData( ...
                        'description', 'column a', ...
                        'data', (1:3)'), ...
                    'columnB', types.hdmf_common.VectorData( ...
                        'description', 'column b', ...
                        'data', (1:2)')), ...
                'NWB:DynamicTable:CheckConfig:InvalidShape')
        end

        function testMismatchedIdHeightWarnsInReadContext(testCase)
            [~, cleanup] = matnwb.common.validation.internal.context("read");

            testCase.verifyWarning( ...
                @() types.hdmf_common.DynamicTable( ...
                    'description', 'mismatched id height', ...
                    'colnames', {'columnA'}, ...
                    'id', types.hdmf_common.ElementIdentifiers( ...
                        'data', int64(0:1)), ...
                    'columnA', types.hdmf_common.VectorData( ...
                        'description', 'column a', ...
                        'data', (1:3)')), ...
                'NWB:DynamicTable:CheckConfig:InvalidId')
        end
    end
end
