classdef BaseReaderTest <  tests.unit.io.backend.base.AbstractBaseClassSmokeTest

    properties (Constant)
        ClassName = "Reader"
        FullClassName = "io.backend.base.Reader"
        ExpectedMethods = [...
            "Reader", ...
            "getEmbeddedSpecLocation", ...
            "getSchemaVersion", ...
            "readAttributeValue", ...
            "readDatasetValue", ...
            "readNodeInfo", ...
            "readRootInfo" ...
        ]
    end

    properties (TestParameter)
        NotImplementedMethodName = cellstr( setdiff( ...
            tests.unit.io.backend.base.BaseReaderTest.ExpectedMethods, ...
            tests.unit.io.backend.base.BaseReaderTest.ClassName) ) % Exclude constructor
    end
end
