classdef BaseLazyArrayTest < tests.unit.io.backend.base.AbstractBaseClassSmokeTest
% BaseLazyArrayTest - Smoke tests for base LazyArray class

    properties (Constant)
        ClassName = "LazyArray"
        FullClassName = "io.backend.base.LazyArray"
        ExpectedMethods = [...
            "LazyArray", ...
            "load_h5_style", ...
            "load_mat_style", ...
            "refreshSizeInfo", ...
            "resolveDataType" ...
        ]
    end

    properties (TestParameter)
        NotImplementedMethodName = cellstr( setdiff( ...
            tests.unit.io.backend.base.BaseLazyArrayTest.ExpectedMethods, ...
            tests.unit.io.backend.base.BaseLazyArrayTest.ClassName) ) % Exclude constructor
    end
end
