classdef BaseWriterTest <  tests.unit.io.backend.base.AbstractBaseClassSmokeTest

    properties (Constant)
        ClassName = "Writer"
        FullClassName = "io.backend.base.Writer"
        ExpectedMethods = [...
            "Writer", ...
            "writeGroup", ...
            "writeValue", ...
            "writeAttribute", ...
            "abort", ...
            "close", ...
            "ensure" ...
        ]
    end

    properties (TestParameter)
        NotImplementedMethodName = cellstr( setdiff( ...
            tests.unit.io.backend.base.BaseWriterTest.ExpectedMethods, ...
            [tests.unit.io.backend.base.BaseWriterTest.ClassName, "abort", "close", "ensure"]) ) % Exclude constructor + implemented methods
    end
end
