classdef BaseLazyArrayTest < tests.unit.io.backend.base.AbstractBaseClassSmokeTest
% BaseLazyArrayTest - Smoke tests for base LazyArray class

    properties (Constant)
        ClassName = "LazyArray"
        FullClassName = "io.backend.base.LazyArray"
        ExpectedMethods = [...
            "LazyArray", ...
            "loadSelections", ...
            "load_h5_style", ...
            "load_mat_style", ...
            "refreshSizeInfo", ...
            "resolveDataType" ...
        ]
    end

    properties (TestParameter)
        % loadSelections has a default implementation, tested below.
        NotImplementedMethodName = cellstr( setdiff( ...
            tests.unit.io.backend.base.BaseLazyArrayTest.ExpectedMethods, ...
            [tests.unit.io.backend.base.BaseLazyArrayTest.ClassName, "loadSelections"]) ) % Exclude constructor
    end

    methods (Test)
        function verifyLoadSelectionsCallsLoadMatStyle(testCase)
            baseInstance = io.backend.base.LazyArray();
            testCase.verifyError( ...
                @() baseInstance.loadSelections({{1}}), ...
                "NWB:Backend:LazyArray:NotImplemented")
        end
    end
end
