classdef (SharedTestFixtures = {tests.fixtures.GenerateCoreFixture}) ...
        DynamicTableRegionTargetTypeValidationTest < matlab.unittest.TestCase

    properties (TestParameter)
        Case = { ...
            struct( ...
                'ParentClass', 'types.core.SimultaneousRecordingsTable', ...
                'PropertyName', 'recordings', ...
                'TargetClass', 'types.core.IntracellularRecordingsTable'), ...
            struct( ...
                'ParentClass', 'types.core.SequentialRecordingsTable', ...
                'PropertyName', 'simultaneous_recordings', ...
                'TargetClass', 'types.core.SimultaneousRecordingsTable'), ...
            struct( ...
                'ParentClass', 'types.core.RepetitionsTable', ...
                'PropertyName', 'sequential_recordings', ...
                'TargetClass', 'types.core.SequentialRecordingsTable'), ...
            struct( ...
                'ParentClass', 'types.core.ExperimentalConditionsTable', ...
                'PropertyName', 'repetitions', ...
                'TargetClass', 'types.core.RepetitionsTable') ...
            }
    end

    methods (Test)
        function testDynamicTableRegionTargetTypeValidation(testCase, Case)
            parentTable = feval(Case.ParentClass);

            correctRegion = testCase.createDynamicTableRegion(...
                feval(Case.TargetClass));
            testCase.assignProperty(parentTable, Case.PropertyName, correctRegion);
            testCase.verifyClass(...
                parentTable.(Case.PropertyName).table.target, ...
                Case.TargetClass)

            wrongRegion = testCase.createDynamicTableRegion(...
                testCase.createGenericDynamicTable());
            testCase.verifyError(...
                @() testCase.assignProperty(parentTable, Case.PropertyName, wrongRegion), ...
                'NWB:CheckType:InvalidNeurodataType')
        end
    end

    methods (Static, Access = private)
        function assignProperty(obj, propertyName, value)
            obj.(propertyName) = value;
        end

        function region = createDynamicTableRegion(targetTable)
            region = types.hdmf_common.DynamicTableRegion( ...
                'data', int8(0), ...
                'description', 'test', ...
                'table', targetTable);
        end

        function table = createGenericDynamicTable()
            table = types.hdmf_common.DynamicTable( ...
                'colnames', {}, ...
                'description', 'test', ...
                'id', types.hdmf_common.ElementIdentifiers('data', int64([])));
        end
    end
end
