classdef (SharedTestFixtures = {tests.fixtures.GenerateCoreFixture}) ...
        NwbFileTest < matlab.unittest.TestCase
% NwbFileTest - Unit tests for the NwbFile constructor.

    methods (Test)
        function testDefaultIdentifierIsAutoGenerated(testCase)
        % Verify that when no identifier is provided, a UUID-like value is
        % automatically generated.
            nwb = NwbFile();
            testCase.verifyNotEmpty(nwb.identifier, ...
                'Expected identifier to be auto-generated, but it is empty.')
            % UUID format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
            uuidPattern = '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
            testCase.verifyMatches(nwb.identifier, uuidPattern, ...
                'Expected auto-generated identifier to be a UUID-formatted string.')
        end

        function testUserSuppliedIdentifierIsPreserved(testCase)
        % Verify that when a user supplies an identifier, it is preserved
        % exactly and not overwritten by the auto-generated UUID.
            expectedIdentifier = 'MY_CUSTOM_ID';
            nwb = NwbFile('identifier', expectedIdentifier);
            testCase.verifyEqual(nwb.identifier, expectedIdentifier, ...
                'Expected user-supplied identifier to be preserved.')
        end
    end
end
