function data = read_indexed_column(vector_index, vector_data, row)
error('NWB:read_indexed_column', ...
    ['The utility function read_indexed_column has been deprecated. Please,' ...
    ' use the getRow method of DynamicTable objects instead'] ...
) 
