function matnwb_generateRstFilesFromCode()
    
    functionsToDocument = [ ...
        "nwbRead", ...
        "NwbFile", ...
        "nwbExport", ...
        "inspectNwbFile", ...
        "generateCore", ...
        "generateExtension", ...
        "nwbClearGenerated", ...
        "nwbInstallExtension", ...
        "matnwb.extension.listExtensions", ...
        "matnwb.extension.getExtensionInfo" ...
    ];

    generateRstForTutorials()
    generateRstForNwbFunctions(functionsToDocument, ...
        '', ... % namespace
        "MatNWB Functions", ... % rst index page title 
        "These are the main functions of the MatNWB API") % rst index description
    generateRstForNeurodataTypeClasses('core')
    generateRstForNeurodataTypeClasses('hdmf_common')
    generateRstForNeurodataTypeClasses('hdmf_experimental')
end