classdef CatalogExtension
% CatalogExtension - Extensions in the Neurodata Extensions Catalog.
%
%   Each member is an extension listed in the Neurodata Extensions Catalog
%   (https://nwb-extensions.github.io). The member name is the extension
%   name as a MATLAB identifier, and the Name property holds the extension
%   name, such as "ndx-miniscope".
%
%   nwbInstallExtension accepts these names, and MATLAB suggests them when
%   typing its first argument.
%
%   This file is generated by tools/maintenance/matnwb_createNwbInstallExtension
%   from resources/function_templates/CatalogExtension.txt. The
%   update_extension_list workflow regenerates it from the catalog.
%
%   Example:
%       names = matnwb.extension.CatalogExtension.listNames()

    properties (SetAccess = immutable)
        % Name - Name of the extension in the catalog
        Name (1,1) string
    end

    methods
        function obj = CatalogExtension(name)
            obj.Name = name;
        end
    end

    methods (Static)
        function names = listNames()
        % listNames - List the names of the extensions in the catalog.
            members = enumeration("matnwb.extension.CatalogExtension");
            names = reshape([members.Name], 1, []);
        end
    end

    enumeration
        ndx_miniscope ("ndx-miniscope")
        ndx_simulation_output ("ndx-simulation-output")
        ndx_ecog ("ndx-ecog")
        ndx_fret ("ndx-fret")
        ndx_icephys_meta ("ndx-icephys-meta")
        ndx_events ("ndx-events")
        ndx_nirs ("ndx-nirs")
        ndx_hierarchical_behavioral_data ("ndx-hierarchical-behavioral-data")
        ndx_sound ("ndx-sound")
        ndx_extract ("ndx-extract")
        ndx_photometry ("ndx-photometry")
        ndx_acquisition_module ("ndx-acquisition-module")
        ndx_odor_metadata ("ndx-odor-metadata")
        ndx_whisk ("ndx-whisk")
        ndx_ecg ("ndx-ecg")
        ndx_franklab_novela ("ndx-franklab-novela")
        ndx_photostim ("ndx-photostim")
        ndx_multichannel_volume ("ndx-multichannel-volume")
        ndx_depth_moseq ("ndx-depth-moseq")
        ndx_probeinterface ("ndx-probeinterface")
        ndx_dbs ("ndx-dbs")
        ndx_hed ("ndx-hed")
        ndx_ophys_devices ("ndx-ophys-devices")
        ndx_microscopy ("ndx-microscopy")
        ndx_pose ("ndx-pose")
        ndx_fiber_photometry ("ndx-fiber-photometry")
        ndx_binned_spikes ("ndx-binned-spikes")
        ndx_wearables ("ndx-wearables")
        ndx_fscv ("ndx-fscv")
        ndx_rate_maps ("ndx-rate-maps")
    end
end
