function customConstraintStr = fillCustomConstraint(nwbType)
% fillCustomConstraint - Create functions to check custom constraints 
%   These are constraints that can not be inferred from the nwb-schema
%
%   Reference: https://github.com/NeurodataWithoutBorders/matnwb/issues/588

    switch nwbType

        case "TimeSeries"
            customConstraintStr = sprintf( [...
                'function checkCustomConstraint(obj)\n', ...
                '    assert(~isempty(obj.timestamps) || ~isempty(obj.starting_time), ...\n', ...
                '        "''timestamps'' or ''starting_time'' must be specified")\n', ...
                '    if ~isempty(obj.starting_time)\n', ...
                '        assert(~isempty(obj.starting_time_rate), ...\n', ...
                '            "''starting_time_rate'' must be specified when ''starting_time'' is specified")\n', ...
                '    end\n', ...
                'end'] );


        case "ImageSeries"
            customConstraintStr = sprintf( [...
                'function checkCustomConstraint(obj)\n', ...
                '    if ~isempty(obj.external_file) && isempty(obj.data), ...\n', ...
                '        obj.data = nan(1,1,2);\n', ...
                '    end\n', ...
                'end'] );

        otherwise
            customConstraintStr = '';
    end
end
