function methodStr = fillDynamicTableMethods()
methodStr = strjoin({...
    'function addRow(obj, varargin)',...
    '    types.util.dynamictable.addRow(obj, varargin{:});',...
    'end',...
    '',...
    'function varargout = getRow(obj, id, varargin)',...
    '    p = inputParser;',...
    '    addParameter(p, ''columns'', obj.colnames);',...
    '    parse(p, varargin{:});',...
    '    varargout = cell(1, length(p.Results.columns));',...
    '    [varargout{:}] = types.util.dynamictable.getRow(obj, id, varargin{:});',...
    'end',...
    '',...
    'function clear(obj)',...
    '    types.util.dynamictable.clear(obj);',...
    'end'}, newline);
end

