function customConstraintStr = fillCustomConstraint(nwbType)
% fillCustomConstraint - Create functions to check custom constraints 
%   These are constraints that can not be inferred from the nwb-schema
%
%   Reference: https://github.com/NeurodataWithoutBorders/matnwb/issues/588

    switch nwbType

        case "TimeSeries"
            % Add method to validate constraint that either timestamps or 
            % starting_time must be present
            customConstraintStr = sprintf( [...
                'function checkCustomConstraint(obj)\n', ...
                '    assert(~isempty(obj.timestamps) || ~isempty(obj.starting_time), ...\n', ...
                '        ''NWB:TimeSeries:TimeNotSpecified'', ...\n ', ...
                '        "''timestamps'' or ''starting_time'' must be specified")\n', ...
                '    if ~isempty(obj.starting_time)\n', ...
                '        assert(~isempty(obj.starting_time_rate), ...\n', ...
                '            ''NWB:TimeSeries:RateMissing'', ...\n', ...
                '            "''starting_time_rate'' must be specified when ''starting_time'' is specified")\n', ...
                '    end\n', ...
                'end'] );


        case "ImageSeries"
            % If external_file is set, it does not make sense to fill out the
            % data property. However, data is a required property, so this 
            % method will add a nan-array to the data property so that it passes 
            % the requirement check on file export.
            customConstraintStr = sprintf( [...
                'function checkCustomConstraint(obj)\n', ...
                '    if ~isempty(obj.external_file) && isempty(obj.data), ...\n', ...
                '        obj.data = nan(1,1,2);\n', ...
                '    end\n', ...
                'end'] );

        otherwise
            customConstraintStr = '';
    end
end
