function fdvstr = fillDynamicValidators(proplist)
fdvstr = '';
for i=1:length(proplist)
    prop = proplist{i};
    fdvstr = [fdvstr ...
        'function validate_dynamic_' prop.type '(obj, val)' newline...
        '    for i=1:length(val)' newline...
        '        valmc = ?val(i);' newline...
        '        valsc = valmc.SuperClassList;' newline...
        '        for j=1:length(valsc)' newline...
        '            if isempty(regexp({valsc(i).Name}, ''types\.\w+\.' prop.type ''', ''once''))' newline...
        '                error(''Dynamic Property obj.' prop.type 'must inherit from ' prop.type ''');' newline...
        '            end' newline...
        '        end' newline...
        '    end' newline...
        'end' newline];
end
end