function fdsstr = fillDynamicSetters(proplist)
fdsstr = '';
for i=1:length(proplist)
    fcnname = proplist{i}.type;
    fdsstr = [fdsstr ...
        'function obj = set_dynamic_' fcnname '(obj, val)' newline...
        '    obj.validate_dynamic_' fcnname '(val);' newline...
        '    obj.' fcnname ' = val;' newline...
        'end' newline...
        ];
end
end