function fsstr = fillSetters(propnames)
fsstr = cell(size(propnames));
for i=1:length(propnames)
    nm = propnames{i};
    fsstr{i} = [...
        'function obj = set.' nm '(obj, val)' newline...
        '    obj.validate_' nm '(val);' newline...
        '    obj = val;' newline...
        'end' newline];
end
fsstr = strjoin(fsstr, newline);
end