function methodStr = fillAlignedDynamicTableMethods()
methodStr = strjoin({...
    'function addCategory(obj, categoryName, categoryTable, options)', ...
    '    arguments', ...
    '        obj (1,1) types.hdmf_common.AlignedDynamicTable', ...
    '    end', ...
    '    arguments (Repeating)', ...
    '        categoryName (1,1) string', ...
    '        categoryTable (1,1) {matnwb.common.validation.mustBeDynamicTable}', ...
    '    end', ...
    '    arguments', ...
    '        options.Replace (1,1) logical = false', ...
    '    end', ...
    '    types.util.aligneddynamictable.addCategory( ...', ...
    '        obj, categoryName, categoryTable, Replace=options.Replace);', ...
    'end'}, newline);
end
