function methodStr = fillAlignedTableMethods()
    methodStr = strjoin({ ...
            'function addRow(obj, varargin)', ...
            '    types.util.alignedtable.addRow(obj, varargin{:});', ...
            'end', ...
            '', ...
            'function addColumn(obj, varargin)', ...
            '    types.util.dynamictable.addColumn(obj, varargin{:});', ...
            'end', ...
            '', ...
            'function row = getRow(obj, id, varargin)', ...
            '    row = types.util.alignedtable.getRow(obj, id, varargin{:});', ...
            'end', ...
            '', ...
            'function table = toTable(obj, varargin)', ...
            '    table = types.util.alignedtable.nwbToTable(obj, varargin{:});', ...
            'end', ...
            '', ...
            'function clear(obj)', ...
            '    types.util.alignedtable.clear(obj);', ...
        'end'}, newline);
end
