function hooks = getPropertyHooks(propName, prop, typeName, namespace)
%GETPROPERTYHOOKS Return custom generator hooks for property validators/setters.

    hooks = struct( ...
        'ValidatorLines', {{}}, ...
        'PostsetStatements', {{}});

    fullClassName = namespace.getFullClassName(typeName);

    if strcmp(fullClassName, 'types.hdmf_common.DynamicTable') ...
            && strcmp(propName, 'colnames')
        hooks.ValidatorLines = { ...
            'val = types.util.dynamictable.validateColnames(val);' };
    end

    if strcmp(fullClassName, 'types.hdmf_common.AlignedDynamicTable') ...
            && strcmp(propName, 'categories')
        hooks.ValidatorLines = { ...
            'val = obj.validateCategoryNames(val);' };
    end

    if file.isDynamicTableDescendant(typeName, namespace) ...
            && isSchemaDefinedDynamicTableColumn(propName, prop)
        hooks.PostsetStatements = { ...
            sprintf('types.util.dynamictable.syncNamedColumn(obj, ''%s'');', propName) };
    end

    if file.isAlignedDynamicTableDescendant(typeName, namespace) ...
            && isSchemaDefinedAlignedDynamicTableCategory(prop, namespace)
        hooks.PostsetStatements = [hooks.PostsetStatements, { ...
            sprintf('obj.ensureCategoryNameRegistered(''%s'');', propName) }];
    end
end

function tf = isSchemaDefinedDynamicTableColumn(propName, prop)
    tf = isa(prop, 'file.Dataset') ...
        && ~prop.isConstrainedSet ...
        && ~strcmp(propName, 'id') ...
        && ~endsWith(propName, '_index');
end

function tf = isSchemaDefinedAlignedDynamicTableCategory(prop, namespace)
    tf = isa(prop, 'file.Group') ...
        && ~prop.isConstrainedSet ...
        && ~isempty(prop.type) ...
        && file.isDynamicTableDescendant(prop.type, namespace);
end
