function hooks = getPropertyHooks(propName, prop, typeName, namespace)
%GETPROPERTYHOOKS Return custom generator hooks for property validators/setters.

    hooks = struct( ...
        'ValidatorLines', {{}}, ...
        'PostsetStatements', {{}});

    fullClassName = namespace.getFullClassName(typeName);

    if strcmp(fullClassName, 'types.hdmf_common.DynamicTable') ...
            && strcmp(propName, 'colnames')
        hooks.ValidatorLines = { ...
            'val = types.util.dynamictable.validateColnames(val);' };
    end

    if file.isDynamicTableDescendant(typeName, namespace) ...
            && isSchemaDefinedDynamicTableColumn(propName, prop)
        hooks.PostsetStatements = { ...
            sprintf('types.util.dynamictable.syncNamedColumn(obj, ''%s'');', propName) };
    end
end

function tf = isSchemaDefinedDynamicTableColumn(propName, prop)
    tf = isa(prop, 'file.Dataset') ...
        && ~prop.isConstrainedSet ...
        && ~strcmp(propName, 'id') ...
        && ~endsWith(propName, '_index');
end
