function templateFilePath = getRstTemplateFile(templateName)
    arguments
        templateName (1,1) string
    end
    fileName = templateName + ".rst.template";

    templateFilePath = fullfile(...
        misc.getMatnwbDir, ...
        "tools", ...
        "documentation", ...
        "_rst_templates", ...
        fileName );

    assert(isfile(templateFilePath), ...
        'Template filepath not found for template with name "%s"', templateName)
end