function templateFilePath = getRstTemplateFile(templateName, options)
    arguments
        templateName (1,1) string
        options.Format (1,1) string {mustBeMember(options.Format, ["rst", "md"])} = "rst"
    end
    fileName = templateName + "." + options.Format + ".template";

    templateFilePath = fullfile(...
        misc.getMatnwbDir, ...
        "tools", ...
        "documentation", ...
        "_rst_templates", ...
        fileName );

    assert(isfile(templateFilePath), ...
        'Template filepath not found for template with name "%s"', templateName)
end