function tf = isWrapped(value, expectedType)
    tf = isa(value, 'types.untyped.DataStub') ...
        || isa(value, 'types.untyped.DataPipe') ...
        || isa(value, 'types.untyped.Anon') ...
        || (isa(value, 'types.untyped.ExternalLink') && ~strcmp(expectedType, 'types.untyped.ExternalLink'));
end
