function electrodeTable = ElectrodeTable(nwbFile)
% ElectrodeRegion - Create electrode region
    
    arguments
        nwbFile (1,1) NwbFile % A device is required
    end

    device = types.core.Device;
    nwbFile.general_devices.set('testDevice', device);

    electrodeTable = types.core.ElectrodesTable(...
        'colnames', {'location', 'group', 'group_name', 'label'}, ...
        'description', 'all electrodes');
    nwbFile.general_extracellular_ephys_electrodes = electrodeTable;

    electrodeGroup = types.core.ElectrodeGroup( ...
        'description', sprintf('electrode group'), ...
        'location', 'brain area', ...
        'device', types.untyped.SoftLink(device) ...
    );
    
    nwbFile.general_extracellular_ephys.set('ElectrodeGroup', electrodeGroup);
    
    electrodeTable.addRow( ...
        'location', 'unknown', ...
        'group', types.untyped.ObjectView(electrodeGroup), ...
        'group_name', 'test electrode group', ...
        'label', 'test electrode');
end
