function imaging_plane = ImagingPlane(device)
% ImagingPlane - Create imaging plane with values for all required properties
    arguments
        device (1,1) types.core.Device % A device is required
    end
    imaging_plane = types.core.ImagingPlane( ...
        'device', types.untyped.SoftLink(device), ...
        'excitation_lambda', 600., ...
        'indicator', 'GFP', ...
        'location', 'my favorite brain location');
end
