function nwb = NWBFile()
    currentTime = datetime("now", 'TimeZone', 'local');
    
    nwb = NwbFile( ...
        'session_description', 'NWB File with required properties for unit testing', ...
        'identifier', 'test_file', ...
        'session_start_time', currentTime, ...
        'timestamps_reference_time', currentTime);
end
