function timeIntervals = TimeIntervals()
    timeIntervals = types.core.TimeIntervals(...
        'description', 'trials', ...
        'colnames', {'start_time', 'stop_time'}, ...
        'id', types.hdmf_common.ElementIdentifiers('data', int64([0; 1])), ...
        'start_time', types.hdmf_common.VectorData(...
            'description', 'start', 'data', [0; 1]), ...
        'stop_time', types.hdmf_common.VectorData(...
            'description', 'stop', 'data', [1; 2]));
end
