function timeSeries = TimeSeries()
    timeSeries = types.core.TimeSeries(...
        'data', (1:10)', ...
        'data_unit', 'a.u.', ...
        'starting_time', 0, ...
        'starting_time_rate', 1);
end
