classdef ImagingPlaneIOTest < tests.system.PyNWBIOTest
  methods    
    function addContainer(testCase, file) %#ok<INUSL>
      oc = types.core.OpticalChannel( ...
        'source', 'unit test TestImagingPlaneIO', ...
        'description', 'a fake OpticalChannel', ...
        'emission_lambda', 3.14);
      ip = types.core.ImagingPlane( ...
        'source', 'unit test TestImagingPlaneIO', ...
        'description', 'a fake ImagingPlane', ...
        'optchan1', oc, ...
        'device', 'imaging_device_1', ...
        'excitation_lambda', 6.28, ...
        'imaging_rate', '2.718', ...
        'indicator', 'GFP', ...
        'location', 'somewhere in the brain');
      file.general_optophysiology.set('imgpln1', ip);
    end
    
    function c = getContainer(testCase, file) %#ok<INUSL>
      c = file.general_optophysiology.get('imgpln1');
    end
  end
end

