classdef ImagingPlaneIOTest < tests.system.PyNWBIOTest
  methods    
    function addContainer(testCase, file) %#ok<INUSL>
      oc = types.OpticalChannel( ...
        'source', {'unit test TestImagingPlaneIO'}, ...
        'description', {'a fake OpticalChannel'}, ...
        'emission_lambda', {'3.14'});
      ip = types.ImagingPlane( ...
        'source', {'unit test TestImagingPlaneIO'}, ...
        'description', {'a fake ImagingPlane'}, ...
        'groups', struct('optchan1', oc), ...
        'device', {'imaging_device_1'}, ...
        'excitation_lambda', {'6.28'}, ...
        'imaging_rate', {'2.718'}, ...
        'indicator', {'GFP'}, ...
        'location', {'somewhere in the brain'});
      file.general.optophysiology = types.untyped.Group();
      file.general.optophysiology.imgpln1 = ip;
    end
    
    function c = getContainer(testCase, file) %#ok<INUSL>
      c = file.general.optophysiology.imgpln1;
    end
  end
end

