classdef NWBFileIOTest < tests.system.PyNWBIOTest

    methods
        function addContainer(testCase, file) %#ok<INUSL>
            ts = types.core.TimeSeries(...
                'data', int64(100:10:190) .', ...
                'data_unit', 'SIunit', ...
                'timestamps', (0:9) .', ...
                'data_resolution', 0.1);
            file.acquisition.set('test_timeseries', ts);
            spatialSeries = types.core.SpatialSeries( ...
                'description', 'A test spatial series', ...
                'data', int64((1:10))' , ...
                'data_unit', 'n/a', ...
                'timestamps', int64((1:10))');

            mod = types.core.ProcessingModule( ...
                'description', 'a test module', ...
                'SpatialSeries', spatialSeries);
            file.processing.set('test_module', mod);
        end
        
        function c = getContainer(testCase, file) %#ok<INUSL>
            c = file;
        end
    end
end
