classdef UnitTimesIOTest < tests.system.RoundTripTest
    methods
        function addContainer(~, file)
            file.units = types.core.Units( ...
                'colnames', {'spike_times', 'waveforms'}, 'description', 'test Units');
            
            file.units.addRow( ...
                'spike_times', rand(), ...
                'waveforms', rand() ...
            );
            % testing adding ragged rows
            file.units.addRow( ...
                'spike_times', {rand(1,3)}, ...
                'waveforms', {rand(1,3)}, ...
                'id', 1 ...
            );
            file.units.addRow( ...
                'spike_times', {rand(1,5)}, ...
                'waveforms', {rand(1,5) rand(1,7)}, ...
                'id', 2 ...
            );
        end
        
        function c = getContainer(~, file)
            c = file.units.spike_times;
        end
    end
end