classdef UnitTimesIOTest < tests.system.PyNWBIOTest
    methods
        function addContainer(~, file)
            file.units = types.core.Units( ...
                'colnames', {'spike_times', 'waveforms', 'waveform_sd', 'waveform_mean'} ...
                , 'description', 'data on spiking units' ...
                );
            
            file.units.addRow( ...
                'spike_times', 11 ...
                , 'waveforms', 9 ...
                , 'waveform_sd', 7 ...
                , 'waveform_mean', 5 ...
                );
            file.units.spike_times.description = 'the spike times for each unit';

            % set optional hidden vector data attributes
            file.units.spike_times.resolution = 3;
            Units = file.units;
            [Units.waveform_mean.sampling_rate ...
                , Units.waveform_sd.sampling_rate ...
                , Units.waveforms.sampling_rate ... 
                ] = deal(1);
        end
        
        function c = getContainer(~, file)
            c = file.units.spike_times;
        end
    end
end