function addRawData(DynamicTable, column, data)
%ADDRAWDATA Internal method for adding data to DynamicTable given column
% name, data and an optional index.
validateattributes(column, {'char'}, {'scalartext'});

% Don't set the data until after indices are updated.
if 8 == exist('types.hdmf_common.VectorData', 'class')
    VecData = types.hdmf_common.VectorData();
else
    VecData = types.core.VectorData();
end

VecData.description = sprintf('AUTOGENERATED description for column `%s`', column);
VecData.data = [];

if isprop(DynamicTable, column)
    if isempty(DynamicTable.(column))
        DynamicTable.(column) = VecData;
    end
    VecData = DynamicTable.(column);
elseif isKey(DynamicTable.vectordata, column)
    VecData = DynamicTable.vectordata.get(column);
else
    DynamicTable.vectordata.set(column, VecData);
end


% grab all available indices for column.
indexChain = {column};
while true
    index = types.util.dynamictable.getIndex(DynamicTable, indexChain{end});
    if isempty(index)
        break;
    end
    indexChain{end+1} = index;
end

% find true nesting depth of column data.
depth = getNestedDataDepth(data);

for iVec = (length(indexChain)+1):depth
    indexChain{end+1} = types.util.dynamictable.addVecInd(DynamicTable, indexChain{end});
end

for iVec = (depth+1):length(indexChain)
    data = {data}; % wrap until the correct number of vector indices are satisfied.
end

nestedAdd(DynamicTable, indexChain, data);
end

function depth = getNestedDataDepth(data)
depth = 1;
subData = data;
while iscell(subData) && ~iscellstr(subData)
    depth = depth + 1;
    subData = subData{1};
end
if size(subData, 1) > 1
    depth = depth + 1;
end
end

function numEntries = nestedAdd(DynamicTable, indChain, data)
name = indChain{end};
numEntries = size(data, 1);

if isprop(DynamicTable, name)
    Vector = DynamicTable.(name);
elseif isprop(DynamicTable, 'vectorindex') && DynamicTable.vectorindex.isKey(name)
    Vector = DynamicTable.vectorindex.get(name);
else
    Vector = DynamicTable.vectordata.get(name);
end

if isa(Vector, 'types.hdmf_common.VectorIndex') || isa(Vector, 'types.core.VectorIndex')
    if ~iscell(data) || iscellstr(data)
        data = {data};
        numEntries = 1;
    end
    
    elems = zeros(numEntries, 1);
    for iEntry = 1:numEntries
        elems(iEntry) = nestedAdd(DynamicTable, indChain(1:(end-1)), data{iEntry});
    end
    data = elems;
end

if ischar(data)
    data = mat2cell(data, ones(numEntries, 1));
end

if isa(Vector.data, 'types.untyped.DataPipe')
    Vector.data.append(data);
else
    Vector.data = [Vector.data; data];
end
end