function addRawData(DynamicTable, column, data, index)
%ADDRAWDATA Internal method for adding data to DynamicTable given column
% name, data and an optional index.
validateattributes(column, {'char'}, {'scalartext'});
if nargin < 4
    % indicates an index column. Note we assume that the index name is correct.
    % Validation of this index name must occur upstream.
    index = '';
end

% Don't set the data until after indices are updated.
VecData = types.hdmf_common.VectorData(...
    'description', sprintf('AUTOGENERATED description for column `%s`', column),...
    'data', []);
if isprop(DynamicTable, column)
    if isempty(DynamicTable.(column))
        DynamicTable.(column) = VecData;
    end
    VecData = DynamicTable.(column);
elseif isKey(DynamicTable.vectordata, column)
    VecData = DynamicTable.vectordata.get(column);
else
    DynamicTable.vectordata.set(column, VecData);
end

if ~isempty(index)
    if isprop(DynamicTable, index)
        VecInd = DynamicTable.(index);
    else
        VecInd = DynamicTable.vectorindex.get(index);
    end
    
    if isa(VecInd.data, 'types.untyped.DataPipe')
        if 0 == VecInd.data.dims
            raggedOffset = 0;
        else
            raggedOffset = VecInd.data.load(VecInd.data.dims);
        end
    else
        if isempty(VecInd.data)
            raggedOffset = 0;
        else
            raggedOffset = VecInd.data(end);
        end
    end
    
    raggedValue = raggedOffset + size(data, 1);
    if isa(VecInd.data, 'types.untyped.DataPipe')
        VecInd.data.append(raggedValue);
    else
        VecInd.data = [VecInd.data; raggedValue];
    end
end

if isa(VecData.data, 'types.untyped.DataPipe')
    VecData.data.append(data);
else
    if ischar(data)
        data = {data};
    end
    VecData.data = [VecData.data; data];
end
end