function addTableRow(DynamicTable, subTable, varargin)

error("NWB:DynamicTable", ...
    ['Using MATLAB tables as input to the addRow DynamicTable method has '...
    'been deprecated. Please, use key-value pairs instead'] ...
    )